# Generated by Django 4.2.2 on 2023-06-26 11:41

import apps_sinapsis.utils.validate_functions
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GENERO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=154, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(default='Tienda-Online', max_length=245)),
                ('status', models.BooleanField(default=True)),
                ('provincia', models.CharField(default='Buenos Aires', max_length=100)),
                ('location_src', models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3285.830022710853!2d-58.68286492323899!3d-34.55785885507963!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcbc45fa07e48f%3A0x2ede182f3817f97e!2sLa%20Plata%20889%2C%20B1661HYL%20Bella%20Vista%2C%20Provincia%20de%20Buenos%20Aires!5e0!3m2!1sen!2sar!4v1687761473818!5m2!1sen!2sar')),
                ('horarios', models.CharField(default='Lunes a Viernes de 9am a 18pm', max_length=100)),
            ],
            managers=[
                ('objets_all', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('isbn', models.CharField(default='978-3-16-148410-0', max_length=17, validators=[apps_sinapsis.utils.validate_functions.validate_ISBN])),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('author', models.CharField(max_length=100)),
                ('paginas', models.IntegerField(blank=True, default=100)),
                ('currency', models.CharField(choices=[('US', 'Dolares'), ('PS', 'Pesos Argentinos'), ('EU', 'Euros')], default='PS', max_length=2)),
                ('precio', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('sinapsis', models.TextField(default='Sin sinapsis aun cargadas')),
                ('short_sinapsis', models.TextField(default='Sinapsis corta')),
                ('cantidad', models.IntegerField(blank=True, default=10)),
                ('image_url', models.ImageField(blank=True, default='images/bg_book.jpg', null=True, upload_to='images/')),
                ('genero', models.ManyToManyField(to='books.genero')),
                ('store', models.ManyToManyField(to='books.store')),
            ],
        ),
    ]
