# Generated by Django 4.2.2 on 2023-06-25 14:49

import apps_sinapsis.utils.validate_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('isbn', models.CharField(default='978-3-16-148410-0', max_length=13, validators=[apps_sinapsis.utils.validate_functions.validate_ISBN])),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('author', models.CharField(max_length=100)),
                ('paginas', models.IntegerField(blank=True, default=100)),
                ('currency', models.CharField(choices=[('US', 'Dolares'), ('PS', 'Pesos Argentinos'), ('EU', 'Euros')], default='PS', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='GENERO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=154, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(to='books.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genero',
            field=models.ManyToManyField(to='books.genero'),
        ),
    ]
