# Generated by Django 4.2.2 on 2023-06-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=12),
        ),
    ]
