# Generated by Django 4.2.2 on 2023-06-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(default='Tienda-Online', max_length=245),
        ),
    ]
