# Generated by Django 4.2.2 on 2023-06-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sinapsis',
            field=models.TextField(default='Sin sinapsis aun cargadas'),
        ),
    ]
