# Generated by Django 4.2.2 on 2023-06-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_sinapsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='cantidad',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name='book',
            name='store',
            field=models.ManyToManyField(to='books.store'),
        ),
    ]
